### ISSUE TITLE
Firebase configuration terdedah kepada umum

### ISSUE THREAD

**Issue by adibzter** [DanishStampy/PPSWE#1]
Mungkin anda mahu masukkan [google-service.json](https://github.com/DanishStampy/PPSWE/blob/master/app/google-services.json) ke dalam .gitignore bagi mengelakkan orang lain salah guna kuota API anda. Hanya sekadar cadangan.

**Comment by DanishStampy** [comment]
> Mungkin anda mahu masukkan [google-service.json](https://github.com/DanishStampy/PPSWE/blob/master/app/google-services.json) ke dalam .gitignore bagi mengelakkan orang lain salah guna kuota API anda. Hanya sekadar cadangan.

terima kasih atas komen anda. baru perasan file tu terdedah.
